using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Anvil.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Anvil.Services
{
	/// <summary>
	/// Default <see cref="IPlaceSearchService"/>: the embedded GeoNames gazetteer (<c>Assets/places-us.json</c>,
	/// generated by <c>tools/make_places_catalog.py</c>) answers suggestions; Nominatim is the submit-only
	/// online fallback.
	/// </summary>
	/// <remarks>
	/// ⚠️ THE CATALOG IS GENERATED — regenerate, never edit. It is embedded CONDITIONALLY (see Anvil.Core.csproj),
	/// so a checkout that never ran the generator still builds; search then degrades to online-only and says so
	/// once in the log.
	/// ⚠️ MATCHING IS WORD-ANCHORED, never an arbitrary substring: a place matches when its name equals the query,
	/// starts with it, or has a WORD that starts with it ("fork" → Rolling Fork). A plain Contains made "mo" match
	/// half the country. Rank is exact → prefix → word, then population.
	/// ⚠️ st/ft/mt ALIAS TO saint/fort/mount only on COMPLETE words. The query's last word is still being typed,
	/// so aliasing it would turn "st" into "saint" and hide Sterling and Stamford mid-keystroke.
	/// </remarks>
	public sealed class PlaceSearchService : IPlaceSearchService
	{
		// RootNamespace is `Anvil`, so the manifest name tracks Assets\places-us.json like the other embedded assets.
		internal const string ResourceName = "Anvil.Assets.places-us.json";

		private const string NominatimSearchUrl = "https://nominatim.openstreetmap.org/search";

		// Nominatim's policy is an absolute maximum of 1 request/second; a little headroom on top.
		private static readonly TimeSpan OnlineMinInterval = TimeSpan.FromMilliseconds(1100);

		private readonly ILogger _logger;
		private readonly HttpClient _http;
		private readonly Lazy<Entry[]> _entries;
		private readonly SemaphoreSlim _onlineGate = new(1, 1);
		private readonly Dictionary<string, IReadOnlyList<PlaceResult>> _onlineCache = new(StringComparer.Ordinal);
		private DateTime _lastOnlineUtc = DateTime.MinValue;

		public PlaceSearchService(ILogger<PlaceSearchService> logger)
			: this(ReadEmbeddedCatalog, null, logger)
		{
			// Parse off the UI thread at startup so the first keystroke doesn't pay for ~30k rows.
			_ = Task.Run(() => _entries.Value);
		}

		/// <summary>Test seam: any catalog text (null = not bundled) and an optional HttpClient.</summary>
		internal PlaceSearchService(Func<string?> readCatalog, HttpClient? http = null, ILogger? logger = null)
		{
			_logger = logger ?? NullLogger.Instance;
			_http = http ?? CreateHttpClient();
			_entries = new Lazy<Entry[]>(() => LoadCatalog(readCatalog));
		}

		public bool HasOfflineCatalog => _entries.Value.Length > 0;

		// ── Offline suggestions ──────────────────────────────────────────────────────────────────────

		public IReadOnlyList<PlaceResult> Suggest(string? query, int max = 8)
		{
			var entries = _entries.Value;
			var raw = query ?? string.Empty;
			if (entries.Length == 0 || max <= 0)
			{
				return Array.Empty<PlaceResult>();
			}

			// "Name, St…" — everything before the comma is a finished name; after it is a state being typed, so
			// it filters by PREFIX ("moore, o" already narrows to OH/OK/OR).
			var comma = raw.LastIndexOf(',');
			if (comma >= 0)
			{
				var nameKey = Key(Words(raw[..comma]), aliasLast: true);
				if (nameKey.Length == 0)
				{
					return Array.Empty<PlaceResult>();
				}
				var statePart = Key(Words(raw[(comma + 1)..]), aliasLast: false);
				return Match(entries, nameKey, statePart.Length == 0 ? null : StatesStartingWith(statePart), max);
			}

			var words = Words(raw);
			if (words.Length == 0)
			{
				return Array.Empty<PlaceResult>();
			}

			// No comma: a trailing COMPLETE state ("moore ok", "springfield missouri") filters — but only when it
			// finds something, because the "state" may be part of the name. A one-word query never splits, so
			// "kansas" searches names.
			if (TrySplitTrailingState(words, out var nameWords, out var code))
			{
				var filtered = Match(entries, Key(nameWords, aliasLast: true), new HashSet<string>(StringComparer.Ordinal) { code }, max);
				if (filtered.Count > 0)
				{
					return filtered;
				}
			}
			return Match(entries, Key(words, aliasLast: false), null, max);
		}

		private static List<PlaceResult> Match(Entry[] entries, string q, IReadOnlySet<string>? states, int max)
		{
			var boundary = " " + q;
			var hits = new List<(int Rank, Entry Entry)>();
			foreach (var e in entries)
			{
				if (states is not null && !states.Contains(e.Place.State))
				{
					continue;
				}

				int rank;
				if (e.Key == q) { rank = 0; }
				else if (e.Key.StartsWith(q, StringComparison.Ordinal)) { rank = 1; }
				else if (e.Key.Contains(boundary, StringComparison.Ordinal)) { rank = 2; }
				else { continue; }

				hits.Add((rank, e));
			}

			return hits
				.OrderBy(h => h.Rank)
				.ThenByDescending(h => h.Entry.Place.Population)
				.ThenBy(h => h.Entry.Key, StringComparer.Ordinal)
				.Select(h => h.Entry.Place)
				.DistinctBy(p => p.Display) // two gazetteer rows for one "Name, ST" read as a duplicate row
				.Take(max)
				.ToList();
		}

		private static bool TrySplitTrailingState(string[] words, out string[] nameWords, out string code)
		{
			// The longest state name is three words ("district of columbia"); at least one word must remain.
			for (var take = Math.Min(3, words.Length - 1); take >= 1; take--)
			{
				var candidate = string.Join(' ', words[^take..]);
				foreach (var (stateCode, nameKey) in States)
				{
					if (candidate == nameKey || candidate == stateCode.ToLowerInvariant())
					{
						nameWords = words[..^take];
						code = stateCode;
						return true;
					}
				}
			}
			nameWords = Array.Empty<string>();
			code = string.Empty;
			return false;
		}

		private static HashSet<string> StatesStartingWith(string partial)
		{
			var set = new HashSet<string>(StringComparer.Ordinal);
			foreach (var (code, nameKey) in States)
			{
				if (code.ToLowerInvariant().StartsWith(partial, StringComparison.Ordinal) ||
					nameKey.StartsWith(partial, StringComparison.Ordinal))
				{
					set.Add(code);
				}
			}
			return set;
		}

		// ── Normalization ────────────────────────────────────────────────────────────────────────────

		/// <summary>Lowercase, diacritics stripped ("Cañon" → "canon"), apostrophes dropped ("O'Fallon" →
		/// "ofallon"), every other non-alphanumeric a word break ("St. Louis" → st, louis).</summary>
		internal static string[] Words(string? s)
		{
			if (string.IsNullOrWhiteSpace(s))
			{
				return Array.Empty<string>();
			}

			var sb = new StringBuilder(s.Length);
			foreach (var ch in s.Normalize(NormalizationForm.FormD))
			{
				if (CharUnicodeInfo.GetUnicodeCategory(ch) == UnicodeCategory.NonSpacingMark || ch is '\'' or '’')
				{
					continue;
				}
				sb.Append(char.IsLetterOrDigit(ch) ? char.ToLowerInvariant(ch) : ' ');
			}
			return sb.ToString().Split(' ', StringSplitOptions.RemoveEmptyEntries);
		}

		/// <summary>Joins words into a match key, expanding st/ft/mt. See the class remarks for why the last word
		/// of a live query is left alone.</summary>
		internal static string Key(string[] words, bool aliasLast)
		{
			var expanded = new string[words.Length];
			for (var i = 0; i < words.Length; i++)
			{
				var w = words[i];
				expanded[i] = (aliasLast || i < words.Length - 1) ? w switch
				{
					"st" => "saint",
					"ft" => "fort",
					"mt" => "mount",
					_ => w,
				} : w;
			}
			return string.Join(' ', expanded);
		}

		// ── Catalog ──────────────────────────────────────────────────────────────────────────────────

		internal readonly record struct Entry(string Key, PlaceResult Place);

		private Entry[] LoadCatalog(Func<string?> read)
		{
			try
			{
				var json = read();
				if (string.IsNullOrEmpty(json))
				{
					_logger.LogWarning("Place catalog {Resource} is not bundled; place search is online-only. Generate it with tools/make_places_catalog.py", ResourceName);
					return Array.Empty<Entry>();
				}
				var entries = ParseCatalog(json);
				_logger.LogInformation("Place catalog loaded: {Count} places", entries.Length);
				return entries;
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Place catalog failed to parse; place search is online-only");
				return Array.Empty<Entry>();
			}
		}

		/// <summary>Catalog shape: <c>{ "places": [ ["Moore","OK",35.3395,-97.4867,62793], … ] }</c> —
		/// name, state, lat, lon, population.</summary>
		internal static Entry[] ParseCatalog(string json)
		{
			using var doc = JsonDocument.Parse(json);
			var places = doc.RootElement.GetProperty("places");
			var list = new List<Entry>(places.GetArrayLength());
			foreach (var row in places.EnumerateArray())
			{
				if (row.ValueKind != JsonValueKind.Array || row.GetArrayLength() < 5)
				{
					continue;
				}
				var place = new PlaceResult(row[0].GetString() ?? string.Empty, row[1].GetString() ?? string.Empty,
					row[2].GetDouble(), row[3].GetDouble(), row[4].GetInt32(), PlaceSource.Offline);
				var key = Key(Words(place.Name), aliasLast: true);
				if (key.Length > 0)
				{
					list.Add(new Entry(key, place));
				}
			}
			return list.ToArray();
		}

		private static string? ReadEmbeddedCatalog()
		{
			using var stream = typeof(PlaceSearchService).GetTypeInfo().Assembly.GetManifestResourceStream(ResourceName);
			if (stream is null)
			{
				return null;
			}
			using var reader = new StreamReader(stream);
			return reader.ReadToEnd();
		}

		// ── Online fallback (Nominatim) ──────────────────────────────────────────────────────────────

		public async Task<IReadOnlyList<PlaceResult>> SearchOnlineAsync(string? query, CancellationToken ct = default)
		{
			var q = (query ?? string.Empty).Trim();
			if (q.Length < 2)
			{
				return Array.Empty<PlaceResult>();
			}

			// Cached per session: the same submitted query never costs a second request.
			var cacheKey = q.ToLowerInvariant();
			lock (_onlineCache)
			{
				if (_onlineCache.TryGetValue(cacheKey, out var cached))
				{
					return cached;
				}
			}

			await _onlineGate.WaitAsync(ct);
			try
			{
				var wait = _lastOnlineUtc + OnlineMinInterval - DateTime.UtcNow;
				if (wait > TimeSpan.Zero)
				{
					await Task.Delay(wait, ct);
				}
				_lastOnlineUtc = DateTime.UtcNow;

				var url = $"{NominatimSearchUrl}?format=jsonv2&addressdetails=1&countrycodes=us&featureType=settlement&limit=6&q={Uri.EscapeDataString(q)}";
				using var response = await _http.GetAsync(url, ct);
				if (!response.IsSuccessStatusCode)
				{
					_logger.LogWarning("Online place search returned {Status} for {Query}", (int)response.StatusCode, q);
					return Array.Empty<PlaceResult>();
				}

				var results = ParseNominatim(await response.Content.ReadAsStringAsync(ct));
				lock (_onlineCache)
				{
					_onlineCache[cacheKey] = results; // failures above are NOT cached — a retry may work
				}
				return results;
			}
			catch (OperationCanceledException) when (ct.IsCancellationRequested)
			{
				throw;
			}
			catch (Exception ex) when (ex is HttpRequestException or TaskCanceledException or JsonException)
			{
				_logger.LogWarning(ex, "Online place search failed for {Query}", q);
				return Array.Empty<PlaceResult>();
			}
			finally
			{
				_onlineGate.Release();
			}
		}

		/// <summary>Nominatim <c>format=jsonv2&amp;addressdetails=1</c> → places. Coordinates arrive as STRINGS;
		/// the state comes from the ISO 3166-2 code ("US-OK") when present, else the state's name.</summary>
		internal static IReadOnlyList<PlaceResult> ParseNominatim(string json)
		{
			using var doc = JsonDocument.Parse(json);
			if (doc.RootElement.ValueKind != JsonValueKind.Array)
			{
				return Array.Empty<PlaceResult>();
			}

			var results = new List<PlaceResult>();
			foreach (var item in doc.RootElement.EnumerateArray())
			{
				if (!TryCoordinate(item, "lat", out var lat) || !TryCoordinate(item, "lon", out var lon))
				{
					continue;
				}
				item.TryGetProperty("address", out var address);
				var name = FirstString(address, "city", "town", "village", "hamlet", "municipality", "locality")
					?? FirstString(item, "name");
				if (string.IsNullOrWhiteSpace(name))
				{
					continue;
				}
				results.Add(new PlaceResult(name, StateFromAddress(address), lat, lon, 0, PlaceSource.Online));
			}
			return results.DistinctBy(p => p.Display).ToList();
		}

		private static string StateFromAddress(JsonElement address)
		{
			var iso = FirstString(address, "ISO3166-2-lvl4");
			if (iso is { Length: 5 } && iso.StartsWith("US-", StringComparison.Ordinal))
			{
				return iso[3..];
			}
			var nameKey = Key(Words(FirstString(address, "state")), aliasLast: true);
			foreach (var (code, key) in States)
			{
				if (key == nameKey)
				{
					return code;
				}
			}
			return string.Empty;
		}

		private static string? FirstString(JsonElement element, params string[] names)
		{
			if (element.ValueKind != JsonValueKind.Object)
			{
				return null;
			}
			foreach (var name in names)
			{
				if (element.TryGetProperty(name, out var el) && el.ValueKind == JsonValueKind.String &&
					!string.IsNullOrWhiteSpace(el.GetString()))
				{
					return el.GetString();
				}
			}
			return null;
		}

		private static bool TryCoordinate(JsonElement item, string name, out double value)
		{
			value = 0;
			if (!item.TryGetProperty(name, out var el))
			{
				return false;
			}
			return el.ValueKind switch
			{
				JsonValueKind.Number => el.TryGetDouble(out value),
				JsonValueKind.String => double.TryParse(el.GetString(), NumberStyles.Float, CultureInfo.InvariantCulture, out value),
				_ => false,
			};
		}

		private static HttpClient CreateHttpClient()
		{
			var http = new HttpClient { Timeout = TimeSpan.FromSeconds(10) };
			// Nominatim rejects anonymous/stock user agents; it asks for one that identifies the application.
			http.DefaultRequestHeaders.UserAgent.ParseAdd("Anvil/1.0 (desktop weather radar; place search)");
			http.DefaultRequestHeaders.AcceptLanguage.ParseAdd("en-US");
			return http;
		}

		// Postal code + normalized name. The 50 states, DC and the inhabited territories.
		private static readonly (string Code, string NameKey)[] States = new (string Code, string Name)[]
		{
			("AL", "Alabama"), ("AK", "Alaska"), ("AZ", "Arizona"), ("AR", "Arkansas"), ("CA", "California"),
			("CO", "Colorado"), ("CT", "Connecticut"), ("DE", "Delaware"), ("DC", "District of Columbia"),
			("FL", "Florida"), ("GA", "Georgia"), ("HI", "Hawaii"), ("ID", "Idaho"), ("IL", "Illinois"),
			("IN", "Indiana"), ("IA", "Iowa"), ("KS", "Kansas"), ("KY", "Kentucky"), ("LA", "Louisiana"),
			("ME", "Maine"), ("MD", "Maryland"), ("MA", "Massachusetts"), ("MI", "Michigan"), ("MN", "Minnesota"),
			("MS", "Mississippi"), ("MO", "Missouri"), ("MT", "Montana"), ("NE", "Nebraska"), ("NV", "Nevada"),
			("NH", "New Hampshire"), ("NJ", "New Jersey"), ("NM", "New Mexico"), ("NY", "New York"),
			("NC", "North Carolina"), ("ND", "North Dakota"), ("OH", "Ohio"), ("OK", "Oklahoma"), ("OR", "Oregon"),
			("PA", "Pennsylvania"), ("RI", "Rhode Island"), ("SC", "South Carolina"), ("SD", "South Dakota"),
			("TN", "Tennessee"), ("TX", "Texas"), ("UT", "Utah"), ("VT", "Vermont"), ("VA", "Virginia"),
			("WA", "Washington"), ("WV", "West Virginia"), ("WI", "Wisconsin"), ("WY", "Wyoming"),
			("PR", "Puerto Rico"), ("GU", "Guam"), ("VI", "United States Virgin Islands"),
			("AS", "American Samoa"), ("MP", "Northern Mariana Islands"),
		}.Select(s => (s.Code, Key(Words(s.Name), aliasLast: true))).ToArray();
	}
}
