"""Generate Anvil.Core/Assets/places-us.json — the offline gazetteer behind the map's place search.

Source: GeoNames "cities500" (every populated place with population >= 500), CC BY 4.0,
https://download.geonames.org/export/dump/cities500.zip — filtered to the US + Puerto Rico.

    py -3 tools/make_places_catalog.py                 # download (cached under tools/.cache) + generate
    py -3 tools/make_places_catalog.py --src cities500.txt   # use a local copy instead

Output shape (read by PlaceSearchService.ParseCatalog):
    { "source": "...", "places": [ ["Moore","OK",35.3395,-97.4867,62793], ... ] }
name, state postal code, lat, lon, population — sorted by population desc, one row per line so a
regeneration diffs readably.

REGENERATE, NEVER EDIT the output by hand.
"""

import argparse
import io
import json
import os
import sys
import urllib.request
import zipfile

URL = "https://download.geonames.org/export/dump/cities500.zip"
HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, ".cache", "cities500.zip")
OUT = os.path.join(HERE, "..", "Anvil.Core", "Assets", "places-us.json")

# GeoNames US admin1 codes ARE the postal codes; anything else (e.g. a stray "00") is dropped.
STATES = set("""AL AK AZ AR CA CO CT DE DC FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH
NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY""".split())

# Populated-place codes that are not a town you would fly to: neighbourhoods/sections (PPLX),
# historical (PPLH), abandoned (PPLQ), destroyed (PPLW).
SKIP_CODES = {"PPLX", "PPLH", "PPLQ", "PPLW"}


def read_rows(src):
    if src:
        with open(src, encoding="utf-8") as f:
            yield from f
        return
    if not os.path.exists(CACHE):
        os.makedirs(os.path.dirname(CACHE), exist_ok=True)
        print(f"downloading {URL}", file=sys.stderr)
        urllib.request.urlretrieve(URL, CACHE)
    with zipfile.ZipFile(CACHE) as z, z.open("cities500.txt") as f:
        yield from io.TextIOWrapper(f, encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", help="a local cities500.txt instead of downloading")
    args = ap.parse_args()

    places = []
    for line in read_rows(args.src):
        c = line.rstrip("\n").split("\t")
        if len(c) < 15 or c[6] != "P" or c[7] in SKIP_CODES:
            continue
        country, admin1 = c[8], c[10]
        if country == "US" and admin1 in STATES:
            state = admin1
        elif country == "PR":
            state = "PR"
        else:
            continue
        places.append([c[1], state, round(float(c[4]), 4), round(float(c[5]), 4), int(c[14] or 0)])

    places.sort(key=lambda p: (-p[4], p[0], p[1]))
    body = ",\n".join("  " + json.dumps(p, ensure_ascii=False) for p in places)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write('{ "source": "GeoNames cities500 (CC BY 4.0), US + PR; generated by tools/make_places_catalog.py",\n')
        f.write(' "places": [\n' + body + "\n] }\n")
    print(f"wrote {len(places)} places -> {os.path.normpath(OUT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
